# Math 753/853 HW3: LU decomposition, no pivoting

**Problem 1.** Write a function named `ludecomp` that computes the LU decomposition of a square matrix $A$ and returns a lower-triangular matrix $L$ and an upper-triangular matrix $U$ such that $A=LU$.

In [3]:
function ludecomp(A)
    #Check that the matrix is square
    if(size(A)[1] != size(A)[2])
        println("This function only accepts square matricies.")
    else
        m = size(A)[1]
        X = float(A)
        L = zeros(X)
        for j = 1:m
            L[j,j] = 1
            for i = j+1:m
                L[i,j] = X[i,j] / X[j,j]
                for k = j:m
                    X[i,k] = X[i,k] - L[i,j] * X[j,k]
                end
            end
        end
        U = X
        return L, U
    end
end

ludecomp (generic function with 1 method)

Test your LU decomposition function on a random 5 x 5  matrix. Use Julia's `randn` function to generate the random matrix with normally distributed elements.

In [28]:
T = randn(5,5)

5x5 Array{Float64,2}:
  1.6117     -1.14401     1.35342    0.426505    0.306499
 -0.850703   -0.0215521  -2.96781   -0.0337638   0.027697
  0.0131804  -1.37335     0.916767  -0.730697    0.804868
 -0.0618478   0.451072    0.435702  -1.19332    -0.338691
 -0.405451   -0.678595    0.975071  -0.772828    2.33843 

In [29]:
C, D = ludecomp(T)

(
5x5 Array{Float64,2}:
  1.0          0.0        0.0       0.0        0.0
 -0.527828     1.0        0.0       0.0        0.0
  0.00817795   2.18102    1.0       0.0        0.0
 -0.0383742   -0.651066  -0.168284  1.0        0.0
 -0.251567     1.54525    0.824273  0.0096663  1.0,

5x5 Array{Float64,2}:
 1.6117       -1.14401    1.35342   0.426505   0.306499
 0.0          -0.625392  -2.25344   0.191358   0.189476
 0.0           0.0        5.82049  -1.15154    0.38911 
 6.93889e-18   0.0        0.0      -1.24615   -0.138086
 0.0           0.0        0.0       0.0        1.80335 )

In [31]:
C*D - T

5x5 Array{Float64,2}:
 0.0   0.0           0.0           0.0           0.0        
 0.0  -1.38778e-17   0.0           6.93889e-18   3.46945e-18
 0.0   0.0           7.77156e-16  -1.11022e-16  -1.11022e-16
 0.0  -5.55112e-17  -1.11022e-16   0.0           0.0        
 0.0   0.0          -2.22045e-16   1.11022e-16   0.0        

**Problem 2.** Write a `forwardsub` function that does forward substitution forward to solve $Ly=b$ for lower-triangular $L$. 

In [27]:
function forwardsub(L,b)
    #Check matrix is square
    if(size(L)[1] != size(L)[2])
        println("This function only accepts square matricies.")
    #Check the matricies can are compatible
    elseif(size(b)[1] != size(L)[1])
        println("L and b are not compatible")
    else
        m = size(b)[1]
        y = copy(b)
        for i = 2:m
            for j = 1:(i-1)
                y[i] = y[i] - L[i,j]*y[j]
            end
        end
        return y
    end
end

forwardsub (generic function with 1 method)

Test your `forwardsub` function on a known $Ly=b$ problem. That is, construct a lower-triangular $L$ and a random $y$ vector and multiply them together to get a vector $b$. Then use `forwardsub` to solve $Ly=b$ for $y$ given $L$ and $b$, and verify that you get the $y$ you started with.

In [26]:
b = [1; 4; 14]
L = [1 0 0; 2 1 0; 3 4 1]
#y = [1; 2; 3]

y = forwardsub(L,b)

3-element Array{Int64,1}:
 1
 2
 3

**Problem 4.** Write a `backwardsub` function that does backward substitution forward to solve $Ux=y$ for upper-triangular $U$. Test it in a similar manner as your test for `forwardsub`.

In [25]:
function backwardsub(U,y)
    #Check matrix is square
    if(size(U)[1] != size(U)[2])
        println("This function only accepts square matricies.")
    #Check the matricies can are compatible
    elseif(size(y)[1] != size(U)[1])
        println("U and y are not compatible")
    else
        m = size(y)[1]
        x = zeros(y)
        x[m] = y[m] / U[m,m]
        for i = (m-1):-1:1
            x[i] = copy(y[i])
            for j = m:-1:i+1
                x[i] = x[i] - U[i,j]*x[j]
            end
            x[i] = x[i] / U[i,i]
        end
        return x
    end
end

backwardsub (generic function with 1 method)

**Problem 5.** Write an `lusolve` function that solves $Ax=b$ for $x$ using `ludecomp`, `forwardsub`, and `backwardsub`. Test it on a problem of your choosing. 

In [24]:
function lusolve(A,b)
    L, U = ludecomp(A)
    y = forwardsub(L,b)
    x = backwardsub(U,y)
    return x
end

A = [1 2 3; 4 5 6; 7 8 12]
b = [14; 32; 50]
#x = [-2; 8; 0]

x = lusolve(A,b)

3-element Array{Int64,1}:
 -2
  8
  0